MainVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: ${self:custom.MainVPC.cidr}
    Tags:
      - Key: Name
        Value: !Sub "${self:custom.base}-main-vpc"

PrivateSubnet:
  Type: AWS::EC2::Subnet
  Properties:
    VpcId: !Ref MainVPC
    CidrBlock: ${self:custom.PrivateSubnet.cidr}
    AvailabilityZone: ${self:custom.PrivateSubnet.availabilityZone}
    MapPublicIpOnLaunch: false # This is a private subnet
    Tags:
      - Key: Name
        Value: !Sub "${self:custom.base}-private-subnet"

PrivateRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
    VpcId: !Ref MainVPC
    Tags:
      - Key: Name
        Value: !Sub "${self:custom.base}-private-route-table"

PrivateSubnetRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    SubnetId: !Ref PrivateSubnet
    RouteTableId: !Ref PrivateRouteTable

