service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    PlayersTable: ${file(resources/PlayersTable.yml):PlayersTable}


functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
      - ${file(iam/PlayersTableIAM.yml):PlayersTableIAM}
    environment:
      REGION: ${self:provider.region}
      PLAYERS_TABLE_NAME: ${self:custom.PlayersTable.name}
      AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
      FOOTBALL_API_KEY: ${ssm:/${self:custom.base}/football-api-key}


custom:
  base: ${self:service}-${opt:stage,'dev'}
  AuctionsTable:
    name: ${self:custom.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn
    indexArn: !Join ["/", ["${self:custom.AuctionsTable.arn}", "index/statusAndEndDate"]]
  PlayersTable:
    name: ${self:custom.base}-players-table
    arn: !GetAtt PlayersTable.Arn