service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.auctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.mailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.auctionsBucket.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          method: POST
          path: /auction
          authorizer: authorizer

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - httpApi:
          method: GET
          path: /auctions
          authorizer: authorizer

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - httpApi:
          method: GET
          path: /auction/{id}
          authorizer: authorizer

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          method: PATCH
          path: /auction/{id}/bid
          authorizer: authorizer

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - httpApi:
          method: PATCH
          path: /auction/{id}/picture
          authorizer: authorizer

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule:
          rate: rate(1 minute)
  
  authorizer:
    handler: src/authorizer/authorizer.handler

custom:
  auctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn

  mailQueue:
    name: MailQueue-${opt:stage, 'dev'}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue

  auctionsBucket:
    name: AuctionsBucket-${opt:stage, 'dev'}
    arn: !GetAtt AuctionsBucket.Arn

  authorizer:
    functionName: Authorizer-${opt:stage, 'dev'}
    arn: !GetAtt Authorizer.Arn

  bundle:
    linting: false
    sourcemaps: false
    caching: true
