service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    authorizers:
      mainAuthorizerGlobalRef:
        type: request
        functionName: mainAuthorizer
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.auctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.mailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.auctionsBucket.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    - ${file(iam/AuctionsBucketIAM.yml):AuctionsBucketIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml):AuctionsBucket}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucket.yml):AuctionsBucketPolicy}
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}

functions:

  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - httpApi:
          method: POST
          path: /auction
          authorizer:
            name: mainAuthorizerGlobalRef

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - httpApi:
          method: GET
          path: /auctions
          authorizer:
            name: mainAuthorizerGlobalRef

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - httpApi:
          method: GET
          path: /auction/{id}
          authorizer:
            name: mainAuthorizerGlobalRef

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - httpApi:
          method: PATCH
          path: /auction/{id}/bid
          authorizer:
            name: mainAuthorizerGlobalRef

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - httpApi:
          method: PATCH
          path: /auction/{id}/picture
          authorizer:
            name: mainAuthorizerGlobalRef

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule:
          rate: rate(1 minute)
  

  mainAuthorizer:
      handler: src/authorizer/authorizer.handler

custom:
  auctionsTable:
    name: !Ref ${self:service}-AuctionsTable-${opt:stage, 'dev'}
    arn: !GetAtt AuctionsTable.Arn

  mailQueue:
    name: ${self:service}-MailQueue-${opt:stage, 'dev'}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue

  auctionsBucket:
    name: ${self:service}-AuctionsBucket-${opt:stage, 'dev'}
    arn: !GetAtt AuctionsBucket.Arn

  mainAuthorizer:
    name: ${self:service}-Authorizer-${opt:stage, 'dev'}

  bundle:
    linting: false
    sourcemaps: false
    caching: true

build:
  esbuild: false
