service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true


resources:
  Resources:
    ${file:./resources/AuctionsTable.yml})}

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - dynamodb:GetItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
          - ${self:custom.AuctionsTable.arn}

custom:
  base: ${self.service}-${opt:stage, 'dev'}
  AuctionsTable:
    name: ${self.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn

