service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
    environment:
      AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}

custom:
  base: ${self:service}-${opt:stage,'dev'}
  AuctionsTable:
    name: ${self:custom.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn

