service: sls

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTableMeta.name}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
    dependsOn:
      - AuctionsTable

custom:
  AuctionsTableMeta:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  bundle:
    linting: false
    include:
      - src/**
      - lib/**

