service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    TeamsCacheTable: ${file(resources/TeamsCacheTable.yml):TeamsCacheTable}


functions:
  main:
    handler: src/main.handler
    memorySize: 1024 
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
      - ${file(iam/TeamsCacheTableIAM.yml):TeamsCacheTableIAM}
    environment:
      REGION: ${self:provider.region}
      TEAMS_CACHE_TABLE_NAME: ${self:custom.TeamsCacheTable.name}
      TEAMS_CACHE_TABLE_INDEX_NAME: ${self:custom.TeamsCacheTable.indexName}
      AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
      FOOTBALL_API_KEY: ${ssm:/${self:custom.base}/football-api-key}
      BOT_TELEGRAM_KEY: ${ssm:/${self:custom.base}/bot-telegram-key}
      DEFAULT_BOT_NAME: ${self:custom.base}-bot

    warmup:
      enabled: true

custom:
  base: ${self:service}-${opt:stage, 'dev'}
  AuctionsTable:
    name: ${self:custom.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn
    indexArn: !Join ["/", ["${self:custom.AuctionsTable.arn}", "index/statusAndEndDate"]]
  TeamsCacheTable:
    name: ${self:custom.base}-teams-cache-table
    arn: !GetAtt TeamsCacheTable.Arn
    indexName: TeamNameIndex
    indexArn: !Join ["/", ["${self:custom.TeamsCacheTable.arn}", "index/${self:custom.TeamsCacheTable.indexName}"]]
  
  warmup:
    enabled: true
    functions:
      main:
        enabled: true
        events:
          - schedule: rate(5 minutes)
        clientContext:
          environment:
            source: warmup-trigger
            stage: ${self:provider.stage}
        payload:
          requestType: warmup
          timestamp: ${opt:timestamp, 'now'}
        concurrency: 1