service: auction-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    AUCTIONS_BUCKET_NAME: ${self:custom.AuctionsBucket.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml)}
    - ${file(iam/AuctionsBucketIAM.yml)}
    - ${file(iam/MailQueueIAM.yml)}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml)}
    AuctionsBucket: ${file(resources/AuctionsBucket.yml)}
    AuctionsBucketPolicy: ${file(resources/AuctionsBucketPolicy.yml)}
    MailQueue: ${file(resources/MailQueue.yml)}
      
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          cors: true
          authorizer: ${self:custom.Authorizer.name}

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
          cors: true
          authorizer: ${self:custom.Authorizer.name}

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
          cors: true
          authorizer: ${self:custom.Authorizer.name}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
          cors: true
          authorizer: ${self:custom.Authorizer.name}

  uploadAuctionPicture:
    handler: src/handlers/uploadAuctionPicture.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/picture
          cors: true
          authorizer: ${self:custom.Authorizer.name}

  processAuctions:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule: rate(1 minute)
  
  Authorizer:
    handler: src/authorizer/authorizer.handler
    events:
      - http:
          method: POST
          path: /auth

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
  MailQueue:
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  AuctionsBucket:
    name: ${self:service}-auctions-bucket-${opt:stage, 'dev'}
    arn: !GetAtt AuctionsBucket.Arn
  Authorizer:
    name: !Ref Authorizer
    arn: !GetAtt Authorizer.Arn
  bundle:
    linting: false
