service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-plugin-warmup

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true

resources:
  Resources:

    #Storage
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    TeamsCacheTable: ${file(resources/TeamsCacheTable.yml):TeamsCacheTable}

    #- Networking
    # Contains the VPC, subnets, and security groups (Networking stuff)
    MainVPC: ${file(resources/vpc.yml):MainVPC}
    PrivateSubnet: ${file(resources/vpc.yml):PrivateSubnet}
    PublicSubnet: ${file(resources/vpc.yml):PublicSubnet}
    PrivateRouteTable: ${file(resources/vpc.yml):PrivateRouteTable}
    PublicRouteTable: ${file(resources/vpc.yml):PublicRouteTable}
    NATGateway: ${file(resources/vpc.yml):NATGateway}
    ElasticIP: ${file(resources/vpc.yml):ElasticIP}
    PrivateRoute: ${file(resources/vpc.yml):PrivateRoute}

    #----

    # Elastic Cache
    BotStateCluster: ${file(resources/elastic-cache.yml):BotStateCluster}
    BotStateSubnetGroup: ${file(resources/elastic-cache.yml):BotStateSubnetGroup}
    #----


    #- Security Groups
    LambdaSG: ${file(resources/security-groups.yml):LambdaSG}
    BotStateSG: ${file(resources/security-groups.yml):BotStateSG}
    #----


functions:
  main:
    handler: src/main.handler
    memorySize: 1024 
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
      - ${file(iam/TeamsCacheTableIAM.yml):TeamsCacheTableIAM}
      - ${file(iam/UsersTableIAM.yml):UsersTableIAM}
      - ${file(resources/elastic-cache/bot-state.yml):BotStateLambdaIAM}
    environment:
      REGION: ${self:provider.region}
      USERS_TABLE_NAME: ${self:custom.UsersTable.name}
      TEAMS_CACHE_TABLE_NAME: ${self:custom.TeamsCacheTable.name}
      TEAMS_CACHE_TABLE_INDEX_NAME: ${self:custom.TeamsCacheTable.indexName}
      AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
      FOOTBALL_API_KEY: ${ssm:/${self:custom.base}/football-api-key}
      BOT_TELEGRAM_KEY: ${ssm:/${self:custom.base}/bot-telegram-key}
      DEFAULT_BOT_NAME: ${self:custom.base}-bot
      GATEWAY_URL: ${self:custom.APIGateway.Url}
      BOT_STATE_REDIS_ADDRESS: ${self:custom.BotStateCluster.address}
            
      BOT_STATE_REDIS_PORT: ${self:custom.BotState.fromPort}
      INTENT_TTL: 3600
    vpc:
      securityGroupIds:
        - !Ref LambdaSG
      subnetIds:
        - !Ref PrivateSubnet
    warmup:
      enabled: true

custom:
  base: ${self:service}-${opt:stage, 'dev'}

  #Storage

  BotStateCluster:
    name: ${self:custom.base}-bot-state-cluster
    arn: !Sub "arn:aws:elasticache:${AWS::Region}:${AWS::AccountId}:cluster/${BotStateCluster}"
    address: !GetAtt BotStateCluster.RedisEndpoint.Address

  UsersTable:
    name: ${self:custom.base}-users-table
    arn: !GetAtt UsersTable.Arn

  AuctionsTable:
    name: ${self:custom.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn
    indexArn: !Join ["/", ["${self:custom.AuctionsTable.arn}", "index/statusAndEndDate"]]

  TeamsCacheTable:
    name: ${self:custom.base}-teams-cache-table
    arn: !GetAtt TeamsCacheTable.Arn
    indexName: TeamNameIndex
    indexArn: !Join ["/", ["${self:custom.TeamsCacheTable.arn}", "index/${self:custom.TeamsCacheTable.indexName}"]]

  #Networking

  MainVPC:
    name: ${self:custom.base}-vpc
    cidr: 10.0.0.0/25
    availabilityZone: ${self:provider.region}a

  PrivateSubnet:
    name: ${self:custom.base}-private-subnet
    cidr: 10.0.0.0/26
    availabilityZone: ${self:provider.region}a

  PublicSubnet:
    name: ${self:custom.base}-public-subnet
    cidr: 10.0.1.0/26 # (32 - 26 = 8 = 2^8 = 256 hosts)
    availabilityZone: ${self:provider.region}a

  PrivateRouteTable:
    name: ${self:custom.base}-private-route-table

  BotState:
    port: 6379
    fromPort: 6379
    toPort: 6380
    arn: ${self:custom.BotStateCluster.arn}
    BotStateSG:
      name: ${self:custom.base}-bot-state-sg
      description: "Ingress allowed from Lambda"
      allowCidr: ${self:custom.PrivateSubnet.cidr}
    LambdaSG:
      name: ${self:custom.base}-lambda-sg
      description: "Lambda to Anywhere"
      allowCidr: ${self:custom.PrivateSubnet.cidr}

  #API
  APIGateway:
    Url:
      Fn::Join:
      - ""
      - - "https://"
        - Ref: "ApiGatewayRestApi"
        - ".execute-api."
        - ${self:provider.region}.
        - Ref: "AWS::URLSuffix"
        - "/"
        - ${self:provider.stage}
  
  
  warmup:
    enabled: false
    functions:
      main:
        enabled: true
        events:
          - schedule: rate(5 minutes)
        clientContext:
          environment:
            source: warmup-trigger
            stage: ${self:provider.stage}
        payload:
          requestType: warmup
          timestamp: ${opt:timestamp, 'now'}
        concurrency: 1


        