service: sls

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  variablesResolutionMode: 20210326
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
    
resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
  
functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
  AuctionsTable:
    name: !Sub "AuctionsTable-${opt:stage, 'dev'}"
    arn: 
      !Sub "arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/AuctionsTable-${opt:stage, 'dev'}"
  bundle:
    linting: false
