service: zik-serverless-nest

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  individually: true

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}
    PlayersBucket: ${file(resources/PlayersBucket.yml):PlayersBucket}
    PlayersBucketPolicy: ${file(resources/PlayersBucketPolicy.yml):PlayersBucketPolicy}

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}    
    iamRoleStatements:
      - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}
      - ${file(iam/PlayersBucketIAM.yml):PlayersBucketIAM}
    environment:
      REGION: ${self:provider.region}
      PLAYERS_BUCKET_NAME_PREFIX: ${self:custom.PlayersBucket.prefix}
      AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}


custom:
  base: ${self:service}-${opt:stage,'dev'}
  AuctionsTable:
    name: ${self:custom.base}-auctions-table
    arn: !GetAtt AuctionsTable.Arn
    indexArn: !Join ["/", ["${self:custom.AuctionsTable.arn}", "index/statusAndEndDate"]]
  PlayersBucket:
    prefix: ${self:custom.base}-players
    name: ${self:custom.base}-players-bucket