AuctionsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.auctionsTable.name}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: statusAndEndDate
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: statusAndEndDate
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5